import discord
from discord.ext import commands
from discord import app_commands
import io
import os
import logging
import datetime
import asyncio
import requests  
import base64  # Added for secure cryptographic encoding
from typing import Optional

# ========================================================================
# 1. SETTINGS AND CONFIGURATION (Railway Compatible)
# ========================================================================
# Fetches the bot token from Railway Environment Variables
TOKEN = os.getenv("DISCORD_TOKEN")
PASTEBIN_API_KEY = os.getenv("PASTEBIN_API_KEY", "SNxRUbS82pBG5qmSW6AeCkmG7nhJhFB1")
PASTEBIN_URL = "https://pastebin.com/api/api_post.php"

# ========================================================================
# 2. LOGGING SYSTEM
# ========================================================================
logger = logging.getLogger('discord')
logger.setLevel(logging.INFO)

handler = logging.FileHandler(filename='discord_bot.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)

console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
logger.addHandler(console_handler)

# ========================================================================
# 3. BOT CLASS AND CONNECTION INFRASTRUCTURE
# ========================================================================
class ProDiscordBot(commands.Bot):
    def __init__(self):
        # Configure mandatory privileged intents required for member events, invite tracking, and content parsing
        intents = discord.Intents.default()
        intents.message_content = True
        intents.members = True
        intents.invites = True  # Added to track server invitations dynamically
        
        super().__init__(
            command_prefix="!", 
            intents=intents,
            help_command=None
        )
        self.welcome_channels = {}  # In-memory dictionary tracking maps of guild_id -> channel_id
        self.invites = {}           # Cache tracking current active invites across guilds

    async def setup_hook(self):
        logger.info("Registering persistent views inside the execution hook...")
        # Add persistence listener for the booster verification button to withstand bot reboots
        self.add_view(VerifyBoosterView())

    async def on_ready(self):
        logger.info(f"Bot successfully logged in! User: {self.user} (ID: {self.user.id})")
        logger.info("-" * 40)
        
        # Mandatory Global Slash Command Synchronization Engine
        try:
            logger.info("Force syncing slash commands globally...")
            await self.tree.sync()
            logger.info("All global slash commands synced successfully!")
        except discord.Forbidden:
            logger.critical("Sync failed! Bot lacks 'applications.commands' scope in its current OAuth2 invitation link.")
        except Exception as e:
            logger.error(f"Error occurred while registering server applications tree context: {e}")
        
        # Cache existing invite link limits upon startup across all connected guilds
        for guild in self.guilds:
            try:
                self.invites[guild.id] = await guild.invites()
            except discord.Forbidden:
                logger.warning(f"Lacks Manage Server permissions to cache invitations for guild: {guild.name} ({guild.id})")
                self.invites[guild.id] = []
            except Exception as e:
                logger.error(f"Failed to fetch invite manifest for guild {guild.id}: {e}")
        
        # Initialize Bot Status Layer
        activity = discord.Activity(type=discord.ActivityType.watching, name="the Server and Commands")
        await self.change_presence(status=discord.Status.online, activity=activity)

    async def on_invite_create(self, invite):
        # Append newly created invite object to the validation registry cache
        if invite.guild.id not in self.invites:
            self.invites[invite.guild.id] = []
        self.invites[invite.guild.id].append(invite)
        logger.info(f"[INVITE-CREATE] New code {invite.code} generated by {invite.inviter} inside guild {invite.guild.id}")

    async def on_invite_delete(self, invite):
        # Evict destroyed invitation code profiles from local validation tracking memory
        if invite.guild.id in self.invites:
            self.invites[invite.guild.id] = [i for i in self.invites[invite.guild.id] if i.code != invite.code]
            logger.info(f"[INVITE-DELETE] Code {invite.code} removed from memory context for guild {invite.guild.id}")

    async def on_member_join(self, member):
        welcome_channel_id = self.welcome_channels.get(member.guild.id)
        if not welcome_channel_id:
            logger.info(f"[JOIN] User {member} joined {member.guild.id}, but welcome system channel mapping is missing.")
            return
            
        channel = member.guild.get_channel(welcome_channel_id)
        if not channel:
            logger.warning(f"[JOIN] Welcome execution stopped: Target channel ID {welcome_channel_id} vanished or is uncached.")
            return
            
        inviter_str = "Unknown/Direct Access"
        try:
            invites_before = self.invites.get(member.guild.id, [])
            invites_after = await member.guild.invites()
            
            # Update invite cache tracking lists immediately
            self.invites[member.guild.id] = invites_after
            
            # Cross-examine use increments to catch the responsible inviter entity
            for invite_b in invites_before:
                for invite_a in invites_after:
                    if invite_b.code == invite_a.code and invite_a.uses > invite_b.uses:
                        if invite_a.inviter:
                            inviter_str = invite_a.inviter.mention
                        break
        except discord.Forbidden:
            logger.warning(f"[TRACK-ERROR] Lacks Manage Server privileges to calculate inviter status details inside guild {member.guild.id}")
        except Exception as e:
            logger.error(f"[TRACK-CRITICAL] Error parsing execution tracking metadata loops: {e}")
            
        welcome_msg = f"Hey {member.mention}, welcome to **{member.guild.name}**! 🎉 You were invited to our community by {inviter_str}."
        try:
            await channel.send(welcome_msg)
            logger.info(f"[JOIN-SUCCESS] Dispatched targeted member introduction message for {member} into channel {channel.id}")
        except Exception as e:
            logger.error(f"Failed to submit welcome message payload to channel {welcome_channel_id}: {e}")

bot = ProDiscordBot()

# ========================================================================
# 4. HELPER CLASSES AND FUNCTIONS
# ========================================================================
def create_embed(title: str, description: str, color: discord.Color = discord.Color.blue()) -> discord.Embed:
    """Generates standard architectural layout containers for secure transaction responses."""
    embed = discord.Embed(
        title=title,
        description=description,
        color=color,
        timestamp=discord.utils.utcnow()
    )
    embed.set_footer(
        text="Sleeping Bot Infrastructure", 
        icon_url=bot.user.display_avatar.url if bot.user and bot.user.display_avatar else None
    )
    return embed

class PasteLinkView(discord.ui.View):
    """Generates localized hyperlink actions mapped directly beneath Pastebin text payloads."""
    def __init__(self, url: str):
        super().__init__()
        self.add_item(discord.ui.Button(label="🌐 Open Link (Proxy)", url=url, style=discord.ButtonStyle.link))

class VerifyBoosterView(discord.ui.View):
    """Persistent user control matrix containing authentication nodes checking server booster flags."""
    def __init__(self):
        # Timeout must be Explicitly None to enable complete application survival cycles
        super().__init__(timeout=None)

    @discord.ui.button(
        label="✅ Verify Booster Status", 
        style=discord.ButtonStyle.success, 
        custom_id="verify_booster_button"
    )
    async def verify_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        # Verification System Constants Mapping Rules
        MAIN_GUILD_ID = 1473684484976148594
        MAIN_BOOSTER_ROLE_ID = 1517453584541679627
        TARGET_BOOSTER_ROLE_ID = 1518972492004331590
        
        # Query and resolve the core verification source server context records
        main_guild = interaction.client.get_guild(MAIN_GUILD_ID)
        if not main_guild:
            await interaction.response.send_message(
                "❌ The main server could not be reached or resolved by the gateway engine. Please contact an administrator.", 
                ephemeral=True
            )
            return

        # Lookup target account within main guild registry
        member_in_main = main_guild.get_member(interaction.user.id)
        if not member_in_main:
            try:
                member_in_main = await main_guild.fetch_member(interaction.user.id)
            except discord.NotFound:
                await interaction.response.send_message(
                    "❌ **Verification Failed!** You must be a registered member of our Main Server to perform this action.", 
                    ephemeral=True
                )
                return
            except discord.Forbidden:
                await interaction.response.send_message(
                    "❌ **Error:** The bot lacks standard fetch permissions to query the Main Server registry.", 
                    ephemeral=True
                )
                return

        # Process role array iteration to verify existence of original booster state flag
        has_booster = any(role.id == MAIN_BOOSTER_ROLE_ID for role in member_in_main.roles)
        if not has_booster:
            await interaction.response.send_message(
                "❌ **Verification Failed!** You do not actively possess the Server Booster role in the main server registry hierarchy.", 
                ephemeral=True
            )
            return

        # Resolve target context placement properties
        target_guild = interaction.guild
        if not target_guild:
            await interaction.response.send_message(
                "❌ This specialized script interaction can only be processed within a guild environment.", 
                ephemeral=True
            )
            return
            
        target_role = target_guild.get_role(TARGET_BOOSTER_ROLE_ID)
        if not target_role:
            await interaction.response.send_message(
                "❌ **System Error:** The requested sync role entity target does not exist on this localized server setup.", 
                ephemeral=True
            )
            return

        # Stop action if localized server assignment flags match state goals
        if target_role in interaction.user.roles:
            await interaction.response.send_message(
                "ℹ️ You have already been successfully verified and hold your rewards here!", 
                ephemeral=True
            )
            return

        # Attempt to grant rewards role across API connection pipelines
        try:
            await interaction.user.add_roles(target_role)
            await interaction.response.send_message(
                "✅ **Verification Successful!** Your Main Server Boost status has been synchronized. Thank you for supporting our networks! 💖", 
                ephemeral=True
            )
            logger.info(f"[BOOSTER-SYNC] Granted synchronized role {TARGET_BOOSTER_ROLE_ID} to user {interaction.user} inside guild {target_guild.id}")
        except discord.Forbidden:
            await interaction.response.send_message(
                "❌ **Permission Denied:** The bot cannot assign this role. Ensure the bot's highest role hierarchy level sits above the target synchronizer role.", 
                ephemeral=True
            )
        except Exception as e:
            await interaction.response.send_message(
                f"❌ An error occurred during role execution parameters: {e}", 
                ephemeral=True
            )

# ========================================================================
# 5. GLOBAL ERROR HANDLER
# ========================================================================
@bot.tree.error
async def on_app_command_error(interaction: discord.Interaction, error: app_commands.AppCommandError):
    if isinstance(error, app_commands.CommandOnCooldown):
        await interaction.response.send_message(
            f"⏳ Please slow down! Wait {error.retry_after:.2f} seconds to trigger this command module again.", 
            ephemeral=True
        )
    elif isinstance(error, app_commands.MissingPermissions):
        await interaction.response.send_message(
            "❌ You do not have the required application privileges to execute this command block.", 
            ephemeral=True
        )
    else:
        logger.error(f"An unexpected error occurred while executing a tree script node path: {error}")
        try:
            if not interaction.response.is_done():
                await interaction.response.send_message(
                    "❌ An unexpected network exception occurred while processing the app command tree request.", 
                    ephemeral=True
                )
            else:
                await interaction.followup.send(
                    "❌ Application processing failed internally due to server pipeline errors.", 
                    ephemeral=True
                )
        except Exception:
            pass

# ========================================================================
# 6. ALL ACTIVE SLASH COMMANDS
# ========================================================================

# Global choice arrays reused inside multiple parameter definition nodes
PING_CHOICES = [
    app_commands.Choice(name="Yes, mention @everyone", value="yes"),
    app_commands.Choice(name="No, do not mention", value="no")
]

EXPIRATION_CHOICES = [
    app_commands.Choice(name="10 Minutes (10M)", value="10M"),
    app_commands.Choice(name="1 Hour (1H)", value="1H"),
    app_commands.Choice(name="1 Day (1D)", value="1D"),
    app_commands.Choice(name="1 Week (1W)", value="1W"),
    app_commands.Choice(name="1 Month (1M)", value="1M"),
    app_commands.Choice(name="1 Year (1Y)", value="1Y"),
    app_commands.Choice(name="Never (N)", value="N")
]

# ---------------------------------------------------------
# COMMAND 1: /send
# ---------------------------------------------------------
@bot.tree.command(name="send", description="Sends the desired text string straight to the designated target channel.")
@app_commands.describe(
    channel="The target text channel where the final content payload will be delivered",
    message="The raw string content text you want to transmit",
    picture="An optional attachment file format graphic to display directly underneath the message block",
    show_sender="Appends your username identity reference details to the tail of the message context",
    ping_everyone="Enables inclusion of raw @everyone global alert text structures above the text string"
)
@app_commands.choices(
    show_sender=[
        app_commands.Choice(name="Yes, reveal sender identity", value="yes"),
        app_commands.Choice(name="No, hide sender identity", value="no")
    ],
    ping_everyone=PING_CHOICES
)
async def send_cmd(
    interaction: discord.Interaction, 
    channel: discord.TextChannel, 
    message: str, 
    picture: Optional[discord.Attachment] = None,
    show_sender: str = "no",
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    if not channel:
        await interaction.followup.send(
            embed=create_embed("❌ Resolution Error", "The execution block could not identify the targeted channel entry.", discord.Color.red())
        )
        return

    content_pieces = []
    if ping_everyone == "yes":
        content_pieces.append("@everyone")
        
    if show_sender == "yes":
        content_pieces.append(f"{message}\n\n*👤 Sender Identification: {interaction.user.mention}*")
    else:
        content_pieces.append(message)

    gonderilecek_icerik = "\n".join(content_pieces)
    
    try:
        if picture:
            file_payload = await picture.to_file()
            await channel.send(content=gonderilecek_icerik, file=file_payload)
        else:
            await channel.send(content=gonderilecek_icerik)
            
        await interaction.followup.send(
            embed=create_embed("✅ Success", f"Your structural message layout has been successfully delivered inside {channel.mention}.", discord.Color.green())
        )
        logger.info(f"[SEND] {interaction.user} used /send to channel {channel.id}")
    except discord.Forbidden:
        await interaction.followup.send("❌ Access Denied: The bot does not have permission to view or write inside that channel.")
    except Exception as e:
        await interaction.followup.send(f"❌ Critical transmission breakdown encountered: {e}")

# ---------------------------------------------------------
# COMMAND 2: /txt
# ---------------------------------------------------------
@bot.tree.command(name="txt", description="Converts input text parameters directly into a downloadable .txt document asset.")
@app_commands.describe(
    file_name="The explicit string label name assigned to the generated text file payload",
    content="The core text strings placed inside the body of the generated document",
    message="An optional text content sentence displayed inside an interface embed window",
    picture="An optional attachment picture file formatted graphic attached to the output card",
    ping_everyone="Enables or disables standard global server alerts attached to this interaction frame"
)
@app_commands.choices(ping_everyone=PING_CHOICES)
async def txt_cmd(
    interaction: discord.Interaction,
    file_name: str,
    content: str,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    # Process string transformations to normalize standard valid OS storage format targets
    file_name = file_name.replace(" ", "_")
    if not file_name.endswith(".txt"):
        file_name += ".txt"
        
    dosya_byte = io.BytesIO(content.encode("utf-8"))
    
    embed = create_embed(
        "📄 Your Custom Document is Ready",
        f"The system layout processing matrix has successfully created your unique file artifact: **`{file_name}`**.",
        discord.Color.gold()
    )
    
    if message:
        embed.add_field(name="💬 Supplementary Content", value=message, inline=False)
    if picture:
        embed.set_image(url=picture.url)
        
    try:
        discord_file = discord.File(fp=dosya_byte, filename=file_name)
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await interaction.followup.send(content=content_override, embed=embed, file=discord_file)
        logger.info(f"[TXT] Generated custom text document file for user {interaction.user}")
    except Exception as e:
        await interaction.followup.send(f"❌ Failed to render the text stream into an attachment element: {e}")
    finally:
        dosya_byte.close()

# ---------------------------------------------------------
# COMMAND 3: /sendtxt
# ---------------------------------------------------------
@bot.tree.command(name="sendtxt", description="Transforms string characters into a .txt file asset and delivers it to a channel.")
@app_commands.describe(
    channel="The destination channel where the created file attachment asset will land",
    file_name="The name assigned to the generated file entity attachment",
    content="The primary body of string text written into the document asset container",
    message="An optional text dialogue card content layout attached directly above the file data block",
    picture="An optional image display block nested deep within the tracking details block",
    show_sender="Displays the user profile tag responsible for spawning this tracking node",
    ping_everyone="Injects active global server notification characters before dispatch lines execute"
)
@app_commands.choices(
    show_sender=[
        app_commands.Choice(name="Yes", value="yes"),
        app_commands.Choice(name="No", value="no")
    ],
    ping_everyone=PING_CHOICES
)
async def sendtxt_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file_name: str,
    content: str,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    show_sender: str = "no",
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    file_name = file_name.replace(" ", "_")
    if not file_name.endswith(".txt"):
        file_name += ".txt"
        
    embed = discord.Embed(
        title="📁 A New Document Has Been Uploaded",
        color=discord.Color.dark_theme(),
        timestamp=discord.utils.utcnow()
    )
    
    if show_sender == "yes":
        embed.add_field(name="Authorized Sender", value=interaction.user.mention, inline=False)
        
    embed.add_field(name="Document Ident Label", value=f"`{file_name}`", inline=False)
    
    if message:
        embed.add_field(name="💬 Accompanying Text", value=message, inline=False)
    if picture:
        embed.set_image(url=picture.url)
        
    dosya_byte = io.BytesIO(content.encode("utf-8"))
    
    try:
        discord_file = discord.File(fp=dosya_byte, filename=file_name)
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, file=discord_file)
        await interaction.followup.send(f"✅ Text asset creation successful. Output deployed to channel {channel.mention}.")
        logger.info(f"[SENDTXT] Deployed formatted txt block to channel {channel.id} by request of {interaction.user}")
    except discord.Forbidden:
        await interaction.followup.send("❌ Channel Blocked: Bot missing file upload or write message context flags.")
    except Exception as e:
        await interaction.followup.send(f"❌ Pipeline delivery script failure: {e}")
    finally:
        dosya_byte.close()

# ---------------------------------------------------------
# COMMAND 4: /modifytxt
# ---------------------------------------------------------
@bot.tree.command(name="modifytxt", description="Flattens all vertical newline text arguments into a uniform horizontal block inside a .txt file.")
@app_commands.describe(
    channel="The target channel interface destination processing the incoming text artifact",
    file_name="The name tag applied to the modified structural layout container",
    content="The multi-line text input blocks that will be transformed horizontally",
    message="Optional dialog summary text metadata blocks written inside tracking cards",
    picture="An optional attachment visualization graphic profile block",
    show_sender="Appends identity metadata tags regarding source authorization nodes",
    ping_everyone="Enables or disables loud global group announcement parameters"
)
@app_commands.choices(
    show_sender=[
        app_commands.Choice(name="Yes", value="yes"),
        app_commands.Choice(name="No", value="no")
    ],
    ping_everyone=PING_CHOICES
)
async def modifytxt_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file_name: str,
    content: str,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    show_sender: str = "no",
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    file_name = file_name.replace(" ", "_")
    if not file_name.endswith(".txt"):
        file_name += ".txt"
        
    # Execute structural row-by-row layout flattening script logic matrices
    flattened_content = " ".join([line.strip() for line in content.splitlines() if line.strip()])
    dosya_byte = io.BytesIO(flattened_content.encode("utf-8"))
    
    embed = discord.Embed(
        title="📁 A Modified Document Has Been Uploaded",
        color=discord.Color.orange(),
        timestamp=discord.utils.utcnow()
    )
    
    if show_sender == "yes":
        embed.add_field(name="Authorized Editor", value=interaction.user.mention, inline=False)
    if message:
        embed.add_field(name="💬 Operational Notes", value=message, inline=False)
    if picture:
        embed.set_image(url=picture.url)
        
    try:
        discord_file = discord.File(fp=dosya_byte, filename=file_name)
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, file=discord_file)
        await interaction.followup.send(f"✅ Text manipulation pipeline completed. File uploaded to {channel.mention}.")
        logger.info(f"[MODIFYTXT] User {interaction.user} deployed flattened row layout to channel {channel.id}")
    except Exception as e:
        await interaction.followup.send(f"❌ Modification formatting script failure: {e}")
    finally:
        dosya_byte.close()

# ---------------------------------------------------------
# COMMAND 5: /sendmytxt
# ---------------------------------------------------------
@bot.tree.command(name="sendmytxt", description="Reads an uploaded local .txt document, copies it, and forwards it to another channel.")
@app_commands.describe(
    channel="The target text placement destination channel mapping context",
    file="The source text document target attachment you wish to read and clone forward",
    message="An optional text content comment string positioned on the tracking embed card",
    picture="An optional auxiliary secondary image block placed deep inside the report matrix",
    ping_everyone="Enables or disables immediate master guild alert pings during delivery loops"
)
@app_commands.choices(ping_everyone=PING_CHOICES)
async def sendmytxt_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file: discord.Attachment,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    if not file.filename.lower().endswith('.txt'):
        await interaction.followup.send("❌ **Validation Error:** This interface pipeline exclusively processes documents ending in `.txt` format.")
        return
        
    try:
        file_bytes = await file.read()
        dosya_byte = io.BytesIO(file_bytes)
        
        embed = discord.Embed(
            title="📥 A Forwarded File Has Arrived",
            color=discord.Color.purple(),
            timestamp=discord.utils.utcnow()
        )
        embed.add_field(name="Source Dispatcher", value=interaction.user.mention, inline=True)
        embed.add_field(name="File Name", value=f"`{file.filename}`", inline=True)
        
        if message:
            embed.add_field(name="💬 Message Content Context", value=message, inline=False)
        if picture:
            embed.set_image(url=picture.url)
            
        discord_file = discord.File(fp=dosya_byte, filename=file.filename)
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, file=discord_file)
        await interaction.followup.send(f"✅ Document asset package successfully pulled and routed into {channel.mention}.")
        logger.info(f"[SENDMYTXT] Forwarded file {file.filename} into channel {channel.id}")
    except Exception as e:
        await interaction.followup.send(f"❌ Transmission interface bridge error: {e}")

# ---------------------------------------------------------
# COMMAND 6: /sendmyfile
# ---------------------------------------------------------
@bot.tree.command(name="sendmyfile", description="Accepts and routes any generic binary file format layout across channels.")
@app_commands.describe(
    channel="The destination text channel mapping context that will host the file block data",
    file="The unique generic binary source attachment format target you want to forward",
    message="An optional string argument text block written into interface details fields",
    picture="An optional graphic picture interface visual display node context",
    ping_everyone="Enables or disables generic global mention announcement loops"
)
@app_commands.choices(ping_everyone=PING_CHOICES)
async def sendmyfile_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file: discord.Attachment,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    try:
        binary_data = await file.read()
        dosya_byte = io.BytesIO(binary_data)
        
        embed = discord.Embed(
            title="📦 A New File Package Has Arrived",
            color=discord.Color.teal(),
            timestamp=discord.utils.utcnow()
        )
        embed.add_field(name="👤 Authorized Source Owner", value=interaction.user.mention, inline=True)
        embed.add_field(name="📄 Declared Asset Name", value=f"`{file.filename}`", inline=True)
        
        if message:
            embed.add_field(name="💬 Embedded Message Lines", value=message, inline=False)
        if picture:
            embed.set_image(url=picture.url)
            
        discord_file = discord.File(fp=dosya_byte, filename=file.filename)
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, file=discord_file)
        await interaction.followup.send(f"✅ Generic binary binary data block safely pushed into {channel.mention}.")
        logger.info(f"[SENDMYFILE] Dispatched raw package {file.filename} into channel {channel.id}")
    except Exception as e:
        await interaction.followup.send(f"❌ Binary file router tracking failure: {e}")

# ---------------------------------------------------------
# COMMAND 7: /paste
# ---------------------------------------------------------
@bot.tree.command(name="paste", description="Uploads comprehensive raw text data packages directly into Pastebin web servers.")
@app_commands.describe(
    channel="The destination platform channel interface receiving the proxy tracking link view",
    content="The massive character blocks written directly inside the digital pastebin entry sheets",
    title="An optional indexing label applied to the head of the web storage space code",
    expiration="Configure lifetime survival limits for the document code sheet",
    message="An optional summary context notation displayed inside localized server boards",
    picture="An optional illustrative media interface block reference profile",
    ping_everyone="Toggles standard network alerts upon script deployment execution"
)
@app_commands.choices(expiration=EXPIRATION_CHOICES, ping_everyone=PING_CHOICES)
async def paste_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    content: str,
    title: Optional[str] = "Community System Log Entry Feed",
    expiration: str = "N",
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    # Configure precise API query payload parameters mapped to the official Developer endpoints
    payload = {
        "api_dev_key": PASTEBIN_API_KEY,
        "api_option": "paste",
        "api_paste_code": content,
        "api_paste_name": title,
        "api_paste_expire_date": expiration,
        "api_paste_private": "0"  # Set explicitly to 0 to enable clean remote readability profiles
    }
    
    try:
        # Transfer requests away from main event loop to preserve bot synchronization states
        response = await asyncio.to_thread(requests.post, PASTEBIN_URL, data=payload, timeout=10)
        
        if response.status_code == 200 and "pastebin.com" in response.text:
            raw_paste_url = response.text.strip()
            # Mutate string targets to proxy routing filters to bypass access lockdowns seamlessly
            proxy_url = raw_paste_url.replace("pastebin.com", "pastebinp.com")
            
            embed = discord.Embed(
                title="🎉 Text Data Package Successfully Pasted!",
                color=discord.Color.blue(),
                timestamp=discord.utils.utcnow()
            )
            embed.add_field(name="Storage Title Reference", value=f"`{title}`", inline=True)
            embed.add_field(name="Life Limit Term", value=f"`{expiration}`", inline=True)
            
            if message:
                embed.add_field(name="💬 Summary Details Log", value=message, inline=False)
            if picture:
                embed.set_image(url=picture.url)
                
            view_panel = PasteLinkView(url=proxy_url)
            content_override = "@everyone" if ping_everyone == "yes" else None
            
            await channel.send(content=content_override, embed=embed, view=view_panel)
            await interaction.followup.send(f"✅ Remote repository synchronization successful. Target proxy URL generated: {proxy_url}")
            logger.info(f"[PASTEBIN] Pushed new raw database code segment block. Proxy URL: {proxy_url}")
        else:
            await interaction.followup.send(f"❌ Pastebin cloud database rejection notice: `{response.text}`")
    except asyncio.TimeoutError:
        await interaction.followup.send("❌ Connection Timeout: Remote Pastebin validation servers failed to resolve in time.")
    except Exception as e:
        await interaction.followup.send(f"❌ Network infrastructure link failure: {e}")

# ---------------------------------------------------------
# COMMAND 8: /bulk
# ---------------------------------------------------------
@bot.tree.command(name="bulk", description="Bundles and dispatches up to 10 assorted unique attachments simultaneously.")
@app_commands.describe(
    channel="The targeted storage channel entry point hosting the bulk asset group",
    file1="Mandatory source file object slot number 1",
    message="Optional dialog notification cards description parameters text",
    picture="An optional graphic picture visual template presentation layer",
    ping_everyone="Enables inclusion of raw @everyone global alert text structures"
)
@app_commands.choices(ping_everyone=PING_CHOICES)
async def bulk_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file1: discord.Attachment,
    file2: Optional[discord.Attachment] = None,
    file3: Optional[discord.Attachment] = None,
    file4: Optional[discord.Attachment] = None,
    file5: Optional[discord.Attachment] = None,
    file6: Optional[discord.Attachment] = None,
    file7: Optional[discord.Attachment] = None,
    file8: Optional[discord.Attachment] = None,
    file9: Optional[discord.Attachment] = None,
    file10: Optional[discord.Attachment] = None,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    # Pack array elements dynamically while cleansing empty non-existent argument values
    raw_slots = [file1, file2, file3, file4, file5, file6, file7, file8, file9, file10]
    active_attachments = [f for f in raw_slots if f is not None]
    
    try:
        discord_files_list = []
        for attachment in active_attachments:
            data_bytes = await attachment.read()
            memory_stream = io.BytesIO(data_bytes)
            discord_files_list.append(discord.File(fp=memory_stream, filename=attachment.filename))
            
        embed = discord.Embed(
            title="📦 Bulk Package Consignment Has Arrived",
            color=discord.Color.dark_teal(),
            timestamp=discord.utils.utcnow()
        )
        embed.add_field(name="Authorized Collector", value=interaction.user.mention, inline=True)
        embed.add_field(name="Total Pack Count", value=f"`{len(discord_files_list)}` items", inline=True)
        
        if message:
            embed.add_field(name="💬 Package Manifest Details", value=message, inline=False)
        if picture:
            embed.set_image(url=picture.url)
            
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, files=discord_files_list)
        await interaction.followup.send(f"✅ Mass consignment payload parsed. {len(discord_files_list)} files deployed to {channel.mention}.")
        logger.info(f"[BULK] Deployed mass composite multi-file transaction stack inside channel {channel.id}")
    except Exception as e:
        await interaction.followup.send(f"❌ Mass assembly ingestion engine crash logged: {e}")

# ---------------------------------------------------------
# COMMAND 9: /bulktxt
# ---------------------------------------------------------
@bot.tree.command(name="bulktxt", description="Bundles and dispatches up to 10 unique text format (.txt) attachments simultaneously.")
@app_commands.describe(
    channel="The destination text channel receiving the bulk document layout",
    file1="First primary text document tracking object source reference",
    message="An optional text content sentence displayed inside an interface embed window",
    picture="An optional auxiliary image format graphics layout mapping parameter",
    ping_everyone="Toggles standard network alerts upon script deployment execution"
)
@app_commands.choices(ping_everyone=PING_CHOICES)
async def bulktxt_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    file1: discord.Attachment,
    file2: Optional[discord.Attachment] = None,
    file3: Optional[discord.Attachment] = None,
    file4: Optional[discord.Attachment] = None,
    file5: Optional[discord.Attachment] = None,
    file6: Optional[discord.Attachment] = None,
    file7: Optional[discord.Attachment] = None,
    file8: Optional[discord.Attachment] = None,
    file9: Optional[discord.Attachment] = None,
    file10: Optional[discord.Attachment] = None,
    message: Optional[str] = None,
    picture: Optional[discord.Attachment] = None,
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    raw_slots = [file1, file2, file3, file4, file5, file6, file7, file8, file9, file10]
    active_attachments = [f for f in raw_slots if f is not None]
    
    # Confirm text document structural target identities before loading system pipelines
    for attachment in active_attachments:
        if not attachment.filename.lower().endswith('.txt'):
            await interaction.followup.send(
                f"❌ **Validation Termination:** File entry named `{attachment.filename}` violates protocol guidelines (not a `.txt` layout)."
            )
            return
            
    try:
        discord_files_list = []
        for attachment in active_attachments:
            data_bytes = await attachment.read()
            memory_stream = io.BytesIO(data_bytes)
            discord_files_list.append(discord.File(fp=memory_stream, filename=attachment.filename))
            
        embed = discord.Embed(
            title="📝 Bulk TXT Documents Shipment Has Arrived",
            color=discord.Color.dark_purple(),
            timestamp=discord.utils.utcnow()
        )
        embed.add_field(name="Authorized Registrar", value=interaction.user.mention, inline=True)
        embed.add_field(name="Document Registry Size", value=f"`{len(discord_files_list)}` sheets", inline=True)
        
        if message:
            embed.add_field(name="💬 Operational Descriptions Stack", value=message, inline=False)
        if picture:
            embed.set_image(url=picture.url)
            
        content_override = "@everyone" if ping_everyone == "yes" else None
        
        await channel.send(content=content_override, embed=embed, files=discord_files_list)
        await interaction.followup.send(f"✅ Text cluster generation successfully closed. Files uploaded inside {channel.mention}.")
        logger.info(f"[BULKTXT] Dispatched text cluster data stacks to channel {channel.id}")
    except Exception as e:
        await interaction.followup.send(f"❌ Cluster file execution framework error: {e}")

# ---------------------------------------------------------
# COMMAND 10: /botinfo
# ---------------------------------------------------------
@bot.tree.command(name="botinfo", description="Reports the bot's instant internal network latency and server connection statistics.")
async def botinfo_cmd(interaction: discord.Interaction):
    gecikme_ms = round(bot.latency * 1000)
    
    embed = discord.Embed(
        title="🤖 Bot Instant Status Report",
        color=discord.Color.brand_green(),
        timestamp=discord.utils.utcnow()
    )
    embed.add_field(name="Gateway Latency (Ping)", value=f"`{gecikme_ms}ms`", inline=True)
    embed.add_field(name="Active Guild Footprint", value=f"`{len(bot.guilds)}` servers connected", inline=True)
    embed.set_thumbnail(url=bot.user.display_avatar.url if bot.user else None)
    
    await interaction.response.send_message(embed=embed)
    logger.info(f"[DIAGNOSTICS] User {interaction.user} checked application runtime footprint indicators.")

# ---------------------------------------------------------
# COMMAND 11: /startwelcome
# ---------------------------------------------------------
@bot.tree.command(name="startwelcome", description="Locks current server's greeting events directly to a specified channel destination.")
@app_commands.describe(channel="The targeted channel destination where incoming greetings are pushed")
@app_commands.checks.has_permissions(manage_guild=True)
async def startwelcome_cmd(interaction: discord.Interaction, channel: discord.TextChannel):
    await interaction.response.defer(ephemeral=True)
    
    # Store layout registration vectors in local memory blocks
    bot.welcome_channels[interaction.guild.id] = channel.id
    
    try:
        # Cache current invite structures immediately to guarantee flawless inviter matching processes later
        bot.invites[interaction.guild.id] = await interaction.guild.invites()
    except Exception:
        pass
        
    await interaction.followup.send(
        embed=create_embed(
            "✨ Introduction Routing Activated", 
            f"The connection mapping loops have successfully linked member introduction event streams to {channel.mention}.", 
            discord.Color.green()
        )
    )
    logger.info(f"[SETUP-WELCOME] Guild {interaction.guild.id} mapped greetings tracking into target channel {channel.id}")

# ---------------------------------------------------------
# COMMAND 12: /purge
# ---------------------------------------------------------
@bot.tree.command(name="purge", description="Removes bulk message history tracking data from targeted channels.")
@app_commands.describe(
    amount="The specific count volume limit parameters of chat messages to erase. Set to 0 to wipe entire channel completely.",
    channel="The text target interface container location being wiped. Defaults to current active area if left blank."
)
@app_commands.checks.has_permissions(manage_messages=True)
async def purge_cmd(interaction: discord.Interaction, amount: int = 0, channel: Optional[discord.TextChannel] = None):
    await interaction.response.defer(ephemeral=True)
    
    target_environment = channel if channel else interaction.channel
    
    try:
        # Evaluate parameter input value bounds to set runtime execution protocols
        if amount == 0:
            await target_environment.purge(limit=None)
            details_str = "All historical chat parameters erased completely."
        else:
            await target_environment.purge(limit=amount)
            details_str = f"Successfully evicted `{amount}` old chat transaction nodes from record loops."
            
        await interaction.followup.send(
            embed=create_embed("🧹 Channel Operations Completed", f"Target segment cleared inside {target_environment.mention}. {details_str}", discord.Color.brand_green())
        )
        logger.info(f"[PRUNING] User {interaction.user} cleared text space parameters inside channel {target_environment.id}")
    except discord.Forbidden:
        await interaction.followup.send("❌ Permission Rejection: The bot lacks historical content purging privileges here.")
    except Exception as e:
        await interaction.followup.send(f"❌ Mass delete operations loop crash: {e}")

# ---------------------------------------------------------
# COMMAND 13: /encode
# ---------------------------------------------------------
@bot.tree.command(name="encode", description="Transforms simple string formats securely into raw base64 cryptographic file packages.")
@app_commands.describe(
    content="The input text string data sequence to process through the transformation matrix",
    file_name="The name tag mapping prefix added to the output attachment text document"
)
async def encode_cmd(interaction: discord.Interaction, content: str, file_name: Optional[str] = "cryptographic_encoded"):
    await interaction.response.defer(ephemeral=True)
    
    try:
        encoded_data_bytes = base64.b64encode(content.encode("utf-8"))
        encoded_string_payload = encoded_data_bytes.decode("utf-8")
        
        # Clean naming extensions
        if not file_name.endswith(".txt"):
            file_name += ".txt"
            
        dosya_byte = io.BytesIO(encoded_string_payload.encode("utf-8"))
        discord_file = discord.File(fp=dosya_byte, filename=file_name)
        
        await interaction.followup.send(
            embed=create_embed("🔒 String Crypto Transformation Completed", "Your text argument payload has been shifted safely into standard base64 parameters.", discord.Color.blue()),
            file=discord_file
        )
        logger.info(f"[CRYPTO-TRANSFORM] Rendered base64 cipher conversion document for user {interaction.user}")
    except Exception as e:
        await interaction.followup.send(f"❌ Cryptographic conversion failed: {e}")

# ---------------------------------------------------------
# COMMAND 14: /sendwebhook
# ---------------------------------------------------------
@bot.tree.command(name="sendwebhook", description="Deploys transient masking webhooks to route custom user identity profile transmissions.")
@app_commands.describe(
    channel="The destination channel where the custom webhook session will temporarily intercept communications",
    message="The raw message text block being safely injected via the custom proxy framework",
    webhook_name="The display username profile text signature worn by the masquerading bot engine",
    avatar_url="An optional proxy direct link URL path defining the visual avatar image icon of the profile profile identity",
    show_sender="Reveals or masks the original account mention identity within the transmission block footer lines",
    ping_everyone="Determines the configuration status of raw structural broadcast message mentions"
)
@app_commands.choices(
    show_sender=[
        app_commands.Choice(name="Yes, append creator profile tag", value="yes"),
        app_commands.Choice(name="No, preserve pure alias mask anonymity", value="no")
    ],
    ping_everyone=PING_CHOICES
)
async def sendwebhook_cmd(
    interaction: discord.Interaction,
    channel: discord.TextChannel,
    message: str,
    webhook_name: str,
    avatar_url: Optional[str] = None,
    show_sender: str = "no",
    ping_everyone: str = "no"
):
    await interaction.response.defer(ephemeral=True)
    
    # Confirm local bot clearance validation settings match design constraints before deploying webhook profiles
    if not channel.permissions_for(interaction.guild.me).manage_webhooks:
        await interaction.followup.send("❌ **Access Blocked:** The application lacks 'Manage Webhooks' validation flags inside that target grid space.")
        return
        
    content_pieces = []
    if ping_everyone == "yes":
        content_pieces.append("@everyone")
        
    if show_sender == "yes":
        content_pieces.append(f"{message}\n\n*👤 Transmission Origin Authorization: {interaction.user.mention}*")
    else:
        content_pieces.append(message)

    final_content = "\n".join(content_pieces)
    
    try:
        # Fire dynamic execution node paths creating tracking targets inside cloud storage structures
        webhook = await channel.create_webhook(name="Bot Temporary Webhook Engine")
        await webhook.send(
            content=final_content,
            username=webhook_name,
            avatar_url=avatar_url
        )
        await webhook.delete()
        
        await interaction.followup.send(f"✅ Webhook transmission successfully completed inside {channel.mention}!")
        logger.info(f"[WEBHOOK] {interaction.user} deployed a webhook into {channel.id} under alias '{webhook_name}'.")
    except Exception as e:
        await interaction.followup.send(f"❌ Webhook terminal injection failed: {e}")

# ---------------------------------------------------------
# COMMAND 15: /sendannounce (BOOSTER SYNC ENGINE)
# ---------------------------------------------------------
@bot.tree.command(name="sendannounce", description="Sends the Booster validation layout to the setup verification channel.")
@app_commands.checks.has_permissions(administrator=True)
async def sendannounce_cmd(interaction: discord.Interaction):
    await interaction.response.defer(ephemeral=True)
    
    # Target validation interface destination configuration constants mapping rules
    VERIFY_CHANNEL_ID = 1518971603063410753
    
    channel = interaction.client.get_channel(VERIFY_CHANNEL_ID)
    if not channel:
        try:
            channel = await interaction.client.fetch_channel(VERIFY_CHANNEL_ID)
        except Exception:
            await interaction.followup.send("❌ Target verification channel could not be found or cached properly across the active grid link.", ephemeral=True)
            return

    embed = discord.Embed(
        title="🌟 Server Booster Verification",
        description=(
            "Thank you for supporting our community! 💖\n\n"
            "If you have boosted our **Main Server**, click the **Verify Booster Status** button below to synchronize your status and instantly unlock your exclusive rewards and rank on this server.\n\n"
            "**Verification Rules:**\n"
            "• You must be a verified member of our Main Server.\n"
            "• Your account must actively have the Server Booster role."
        ),
        color=discord.Color.magenta(),
        timestamp=discord.utils.utcnow()
    )
    embed.set_thumbnail(url=interaction.guild.icon.url if interaction.guild.icon else None)
    embed.set_footer(text="Global Booster Sync Engine", icon_url=bot.user.display_avatar.url if bot.user and bot.user.display_avatar else None)

    view = VerifyBoosterView()
    
    try:
        await channel.send(embed=embed, view=view)
        await interaction.followup.send(f"✅ The booster announcement layout has been successfully deployed to {channel.mention}.", ephemeral=True)
        logger.info(f"[ANNOUNCEMENT] Successfully spawned localized verification display matrices inside channel {channel.id}")
    except discord.Forbidden:
        await interaction.followup.send("❌ The bot doesn't have permission to write messages in the designated verification channel.", ephemeral=True)
    except Exception as e:
        await interaction.followup.send(f"❌ System failure during message dispatch: {e}", ephemeral=True)

# ========================================================================
# 7. SERVER RUN TRIGGER
# ========================================================================
if __name__ == "__main__":
    if not TOKEN:
        logger.critical("Critical Error: DISCORD_TOKEN environment variable is not defined in the Railway panel!")
    else:
        try:
            bot.run(TOKEN)
        except discord.LoginFailure:
            logger.critical("Login Failed: The token entered in Railway Variables is invalid or has been reset by Discord!")
        except Exception as e:
            logger.critical(f"Unexpected system error while starting the bot: {e}")
